apiVersion: v1
kind: Service
metadata:
  name: nestjs-boilerplate-service
spec:
  selector:
    app: nestjs-boilerplate
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3030
  type: LoadBalancer
